env:
  global:
    - CC_TEST_REPORTER_ID=b84d24d87a44d1bc041abe37a4e8c4bae44e5691b136ec6a37df73b3bf6b8ca4
language: node_js
node_js:
  - "lts/*"
services:
  - docker
before_install:
  - cd ./docker/
  - docker-compose up -d
  - cd ../
before_script:
  - npm install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test-integration
after_script:
  - cd ./docker/
  - docker-compose logs -t celery rabbitmq redis
  - cd ../
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
before_deploy:
  - npm pack
  - npm run typedoc
deploy:
  - provider: npm
    skip-cleanup: true
    email:
      secure: "uHABxz6BMVLqb9cdguZL/032Oo8bD3ncvd8LC9B18fGQ3alAWrNvWCWXlzJ6f9qXkwS9RF5FBN/R+sej+Q77VSA6tXdkPZoVToJ8EnQfQsEmnaphqVBh/ei0OTDJMgAy6/c74RGeqkFR0it3r20Sen9OYxLhO8n70mEaKabRy1VMUsBJlbq1jx9+hrWDOod8qG+Z66d6zkbkWK1qgoWEWHznOegzqm4vib/DEVZCBdNti96Y+Q1nnTILKOVACLISuJqjb+qdvIh8I+xvpvJYvYolxwC6ioR/Oy4dBJduYQhXupORMn7KU8wLGBy1XN8o2wUuMCEwXd4W/lXozte4dpPrQjNGR6c79rL8K/qfyR94NFHnI5kKYKKAyXVg7P0qF7zFDXs0JbkAJyHPOE25BSbp5Uk9/z32tGEQWkH+429NU9NxV9YbPVEep6lWZ4jypozDv+rgCQEYm2vZ9bJGO2ogg/9QCG6S3CvMrfDsYP60wSZdXu3niVENMkcA7xDcX3fDiIMQX9/0K9fsyUrcMTpq+fmFP8wo0YBA0XoCrevahKOF+yaCtpJFF/foSYDkaWqOEshYrwJjxlDQ5Vi16zIREJAZaGx6VgqGFnHRWSr6qLQwAgnzrsZtc2aV7u9047e2CNHGcJQDYMCkLAd7I/KVzhvIm3kPaB6aRyX9BIM="
    api_key:
      secure: "Tl/PBDEhLaECtZBncDxmd4y2g3UBbU0o7oYRslk28q3RjEUlHkMczchUkYgPhqcZF7nzm9qS6BmAIO6/e74Sqc9zxGxn1n4Q/hmUY260pZoMsgmusp+VWXc1XfctjPyY3O7LI3qjfkNA9Z82jed6K+4aFcizDOtw9tlu11/vqZWJPPZID2gRYbAMJF5xfVMdzHwF2sB2aQ+gsl+wITXVTjKUkIzp5/1waxuXBnW+dR+V8IHLKfm814RrNA4BPLYwenJjWq1RG5orfZX6b5sgqIcq/5fTEh5ZHpmTZOchjN6gLSD3hI8N2hf5SPVED18XLjoQj1rQqm+k6bb5+IzqdqOmxaeMIBAh4JY6OxdIy9C81MYGYWzMAUkRJErbStIM7M9q07Kv9vYOgI2LWjuIxUxx5YunM+f1RkDUUOHu1rREDTuTvqf9lm5aBpsz60w2waoYGkOmYuu4UQNUo9Ywjc/acyyopY1M7o4LQDuvdyCCZxISZDVM7afyUb84Y9DQucakI076Mr4cVpUuYr4rJiBeMiLITRR9v2Zb905L4o62z/0oQD8sabCpHxbeRH6oHCcTH1i7J4lB6FX9dcg0LDhLBh5zjcZQTPY+0T50CCr95lwdaM4C7zGidSBr45/p89DVGgBEL8JQNvbv6I32MRmTsxT+1GLarwZHNxFpPI4="
    on:
      tags: true
      repo: IBM/node-celery-ts
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: develop
    local-dir: docs
